### ISSUE TITLE
Комментарии к пользовательским сценариям 

### ISSUE THREAD

**Issue by dpaleyev** [anaputeinis/efc#2]
1. Сценарий №1 стоит добавить возможность смены/восстановления пароля при входе в систему
2. Сценарий №3 кажется логично добавить какое-то оповещение или банер при просмотре продукта, на который может быть аллергия

**Comment by anaputeine** [comment]
1. Добавила опцию сменить пароль в сценарий 2.
2.  Фраза "просмотреть состав продукта" в сценарии 3 подразумевает отображение информации о аллергиях пользователя.
